### ISSUE TITLE
Duplicate declaration extension

### ISSUE THREAD

**Issue by marcospassos** [Swatinem/rollup-plugin-dts#90]
When bundling a multi-entry package the declaration file extension gets duplicate:

```js
     {
            input: ['build/foo.d.ts', 'build/bar.d.ts'],
            output: [{
                dir: 'build',
                format: 'es'
            }],
            plugins: [dts({respectExternal: true})],
        }
```

Generates two files `foo.d.d.ts` and `bar.d.d.ts`.

**Comment by Swatinem** [comment]
oh, those are even in the testcases, though not as obvious:
https://github.com/Swatinem/rollup-plugin-dts/blob/c213380db7548ffcca2220ff1e8442e8ddeb5758/tests/testcases/multiple-entries/expected.d.ts#L2

**Comment by marcospassos** [comment]
Yeah, easy to pass by.

It just blocked our release, any chances of releasing a patch version? May I help in some way?

**Comment by Swatinem** [comment]
> May I help in some way?

patches welcome ;-)

https://github.com/Swatinem/rollup-plugin-dts/blob/c213380db7548ffcca2220ff1e8442e8ddeb5758/src/index.ts#L120-L121

I think rollup accepts callback functions for these? I think the problem is that `name` includes the `.d` suffix

**Comment by Swatinem** [comment]
You can obviously also override those, to completely customize.

**Comment by marcospassos** [comment]
I don't think the problem is there. The file names that get screwed are not the chunk files but the input ones.

**Comment by Swatinem** [comment]
yes, the `entryFileNames`. the chunk name is what is used in my fixtures, which shows what rollup does.

I think we can use the [options hook](https://rollupjs.org/guide/en/#options) to transform the inputs from an array into an explicit object, with explicitly set `name` parts.

**Comment by marcospassos** [comment]
@Swatinem thank you very much for fixing this. Any change in releasing a patch version anytime soon?

Ps: This plugin is amazing!

**Comment by Swatinem** [comment]
done ;-)

also, I should really pay more attention when late-night coding 😆

**Comment by marcospassos** [comment]
@Swatinem unfortunately, it is still broken :(

Now some imports get duplicated and all include the suffix `.d.ts`:

```
// original.d.ts
import { Foo, Bar, Baz } from './a';
export { Foo, Bar };
declare const _default: Baz;
export default _default;
```
```
// The following imports are really weird
import './chunk-2beb769b.d.ts';
import './b.d.ts';
import { Baz } from './a.d.ts';
export { Foo, Bar } from './a.d.ts';

declare const _default: Baz;

export default _default;
```

Error:
```
TS2691: An import path cannot end with a '.d.ts' extension. Consider importing './a' instead
```

**Comment by Swatinem** [comment]
Oh, I completely forgot about that restriction. In which case, I’m not sure I can even fix that; probably with a post-bundle hook. 🤦‍♂️

**Comment by marcospassos** [comment]
Is there something I can do on my side?

**Comment by marcospassos** [comment]
(any clue on how those two imports are being added?)
```
// The following imports are really weird
import './chunk-2beb769b.d.ts';
import './b.d.ts';
```

**Comment by Swatinem** [comment]
Since you have two entry-points, rollup will try to group common things into one chunk. not quite sure why it has those empty imports there. Do you have a minimal reproduction for that?

You can try to find all the relative imports in the `NamespaceFixer`, which runs as a post-processor. And then try to patch those up. Will be a pain in the rear though.
